[project]
name = "ernies-360pi-com"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.40.7",
    "botocore>=1.40.7",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
